[package]
name = "unshare"
description = """
    The low-level inteface for linux namespaces (containers). Work in progress.
"""
license = "MIT"
readme = "README.rst"
keywords = ["linux", "container", "namespace", "docker", "process"]
homepage = "http://github.com/tailhook/unshare"
documentation = "http://tailhook.github.io/unshare/"
version = "0.0.1"
authors = ["paul@colomiets.name"]

[dependencies]
libc = "*"
nix = "*"

[dev-dependencies]
argparse = "*"

[lib]
name = "unshare"
path = "src/lib.rs"

